runtime: go
api_version: go1

handlers:
- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /paste/.*
  script: _go_app

- url: /.*
  static_files: index.html
  upload: index\.html
  login: required
